### PR TITLE
File methods should handle Pathname objects.

### PR DESCRIPTION
**Pull request by dtognazzini**
This is failing with:
```
  1) Error:
FakeFSTest#test_handles_pathnames:
NoMethodError: undefined method `[]' for #<Pathname:/path/to/dir>
    fakefs/lib/fakefs/globber.rb:7:in `expand'
    fakefs/lib/fakefs/file_system.rb:27:in `find'
    fakefs/lib/fakefs/file.rb:117:in `directory?'
    fakefs/test/fakefs_test.rb:175:in `test_handles_pathnames'
```

This tests passes on commit 4cce640fb131161afd2e22b76ba5498734e116f2. I think the break was introduced by #298.

### CODE REVIEW

**Comment by tovodeverett** [comment]
See https://github.com/fakefs/fakefs/pull/330 for a unified pull request that address this issue as well as another in Globber.

**Comment by tovodeverett** [comment]
This commit in this pull request is included in https://github.com/fakefs/fakefs/pull/336.

**Comment by tovodeverett** [comment]
@dtognazzini - can you verify if #336 addresses this and if so close this pull request?  Thanks.

**Comment by dtognazzini** [comment]
@tovodeverett - Looks like #336 works a treat. Thanks!
