### ISSUE TITLE
Ruby 4.0 Question: Pathname#path missing?

### ISSUE THREAD

**Issue by etagwerker** [fakefs/fakefs#526]
Hi there, 

I was working on adding support for Ruby 4.0 for rubycritic (https://github.com/whitesmith/rubycritic/pull/556) and I had to monkeypatch `fakefs` with this: 

```
# Patch FakeFS::Pathname to include the path method for Ruby 4.0.0 compatibility
# This is needed because Reek's configuration internally calls Pathname#== which
# requires the path method to be present
module FakeFS
  class Pathname
    def path
      to_s
    end
  end
end
```

I'm wondering if this should be added to `fakefs` so that any library/app that uses `fakefs` won't run into the same error. 

The error I got was this one: 

```
  1) Error:
RubyCritic::Generator::JsonReport::#generate_report#test_0001_creates a report file with JSON data inside:
NoMethodError: undefined method 'path' for an instance of FakeFS::Pathname
    /Users/etagwerker/.rbenv/versions/4.0.0/lib/ruby/gems/4.0.0/gems/reek-6.5.0/lib/reek/configuration/app_configuration.rb:70:in 'Pathname#=='
    /Users/etagwerker/.rbenv/versions/4.0.0/lib/ruby/gems/4.0.0/gems/reek-6.5.0/lib/reek/configuration/app_configuration.rb:70:in 'Array#include?'
    /Users/etagwerker/.rbenv/versions/4.0.0/lib/ruby/gems/4.0.0/gems/reek-6.5.0/lib/reek/configuration/app_configuration.rb:70:in 'Reek::Configuration::AppConfiguration#path_excluded?'
    lib/rubycritic/analysers/smells/reek.rb:15:in 'block in RubyCritic::Analyser::ReekSmells#initialize'
    lib/rubycritic/core/analysed_modules_collection.rb:32:in 'Array#each'
    lib/rubycritic/core/analysed_modules_collection.rb:32:in 'RubyCritic::AnalysedModulesCollection#each'
    lib/rubycritic/analysers/smells/reek.rb:13:in 'Enumerable#reject'
    lib/rubycritic/analysers/smells/reek.rb:13:in 'RubyCritic::Analyser::ReekSmells#initialize'
    lib/rubycritic/analysers_runner.rb:30:in 'block in RubyCritic::AnalysersRunner#run'
    lib/rubycritic/analysers_runner.rb:29:in 'Array#each'
    lib/rubycritic/analysers_runner.rb:29:in 'RubyCritic::AnalysersRunner#run'
    test/lib/rubycritic/generators/json_report_test.rb:32:in 'create_analysed_modules_collection'
    test/lib/rubycritic/generators/json_report_test.rb:19:in 'block (3 levels) in <top (required)>'
```

I could submit a PR with this new method if you think that's a good idea.

I'm not sure if this is an issue with `fakefs` or `reek`

Please let me know your thoughts. 

Thanks!

**Comment by grosser** [comment]
https://github.com/fakefs/fakefs/pull/529
v3.1.0
